name: "Build on version tag pushed"
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
jobs:
  cake-build:
    name: Run Cake script
    runs-on: windows-latest
    steps:
      - name: Get the sources
        uses: actions/checkout@v1
      - name: Restore dotnet tools
        run: dotnet tool restore
      - name: Run the Cake script
        uses: cake-build/cake-action@v1