name: "TODO to Issues"

on:
  push:
    branches:
      - develop
      - main

jobs:
  todo:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Get the sources
        uses: actions/checkout@v6

      - name: TODO to Issue
        uses: alstr/todo-to-issue-action@v5.1.14
        with:
          IDENTIFIERS: '[{"name": "TODO", "labels": ["ungroomed"]}]'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
